version: '3.1'
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: xSGctQaAl8Qz
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"